### ISSUE TITLE
לתת אפשרות לזוז עם חיצי A,D

### ISSUE THREAD

**Issue by Maor-Or** [Computer-game-development-course/Where_Is_Sky#10]
במקום לזוז עם ימינה ושמאלה, שיהיה אפשר לשנות לזוז עם A,D - אני שמאלי ורגיל להחזיק את העכבר עם יד ימין ולהשתמש במקלדת עם יד שמאל, אז זה לא נוח לשחק ככה כאשר אי אפשר לזוז עם החיצים בצד השמאלי של המקלדת

בנוסף, בכל שלב החתול מתחבא באותו המקום, כדאי להוסיף כמה נקודות שבהן החתול יכול להתחבא, כי אחרי ששיחקתי פעם אחת, ידעתי איפה למצוא את החתול כששיחקתי שוב

**Comment by AlinaZahozi** [comment]
fixed
