### ISSUE TITLE
חדר שנפתח לא מקבלים התרעה שהוא נפתח +כשיש הרבה חדרים פתוחים צריך לקבל יותר זמן 

### ISSUE THREAD

**Issue by ohadtaizi** [Computer-game-development-course/Where_Is_Sky#11]
ברגע שעוברים שלב , יכול להיות שנפתחים חדרים אחרים לא שמים לב לזה עד שלא מוצאים כמה פעמים ואז אתה מחפש לחצן שמציע לך לבחור חדר או יהיה שכתוב מאיזה שלב נפתח כל חדר או שהיה סימן קריעה שקרה משהו חדש  .
שיחקתי עד שלב 7 .

**Comment by AlinaZahozi** [comment]
fixed
