### ISSUE TITLE
שמירת תוצאה הכי טובה לכל חדר

### ISSUE THREAD

**Issue by EladLaster** [Computer-game-development-course/Where_Is_Sky#13]
בעיה: כאשר אני נכנס לשלב שעשיתי כבר כדי לשפר את התוצאה שעשיתי בו (לעשות 3 כוכבים במקום 2 לדוגמא), אני יכול לעשות תוצאה פחות טובה (לעשות כוכב 1 במקום 2 לדוגמא) ויישמר לי התוצאה האחרונה ולא התוצאה הטובה ביותר שעשיתי עד עכשיו

פתרון: בכל שלב יישמר התוצאה הטובה ביותר של אותו שלב ואם אני מנסה לשפר ולא מצליח אז יישאר על מספר הכוכבים הנוכחי (אם עשיתי תוצאה טובה של 2 כוכבים היא תישמר עד שאצליח לעקוף אותה ולעשות 3 כוכבים)

**Comment by AlinaZahozi** [comment]
fixed
