### ISSUE TITLE
הטקסט בהתחלה

### ISSUE THREAD

**Issue by hodwys** [Computer-game-development-course/Where_Is_Sky#15]
הטקסט בהתחלה מסביר ממש טוב איך לשחק אך בכל פעם שהתחלתי לשחק מחדש זה הופיע לי שוב. צריך לעשות כפתור שרק מי שרוצה הסבר שיוכל לראות הסבר ומי שכבר הבין איך משחקים ולא מעוניין לקרוא שוב שיוכל לדלג על זה.

**Comment by AlinaZahozi** [comment]
fixed
