### ISSUE TITLE
Arrows on the screen don't do anything

### ISSUE THREAD

**Issue by ofekrotem** [Computer-game-development-course/Where_Is_Sky#18]
I would expect pressing on the arrows on the side of the screen (with the mouse) would make the same movements as if I press with the keyboard arrows.

![image](https://github.com/Computer-game-development-course/Where-s-Sky-/assets/92383710/988180d8-67ff-4a2d-bd59-0b7a4e06be80)

**Comment by AlinaZahozi** [comment]
fixed
