### ISSUE TITLE
select option

### ISSUE THREAD

**Issue by HadarBitan** [Computer-game-development-course/Where_Is_Sky#19]
כשלוחצים על הselect ובוחרים את השלב הראשון אז ישר נפתח המשחק ואין ידע איך לשחק(יש אנשים שישר ילכו לselect) חשוב לדעתי רק בשלב הראשון לא לאפשר את האופציה לselect אלא רק לplay כדי ששחקנים ישר ייכנסו לסיפור וליכולת להבין כיצד לשחק.

**Comment by AlinaZahozi** [comment]
fixed
