### ISSUE TITLE
מסך פתיחה

### ISSUE THREAD

**Issue by MatanAdar** [Computer-game-development-course/Where_Is_Sky#22]
המשחק נראה טוב אבל לא מובן בהתחלה שהכפתור "פליי" הוא הכפתור של ההדרכה והכפתור "לבחור" הוא הכפתור לכל שלב. כדאי לדעתי לשנות שהכפתור "פליי" יקח אותנו לעמוד שבו נבחר איזה שלב אנחנו רוצים והכפתור השני יהיה הדרכה שנקרא tutrial

**Comment by erelsgl** [comment]
כן, גם לי הטקסט היה לא ברור

**Comment by AlinaZahozi** [comment]
תוקן
