### ISSUE TITLE
הטקסט בהתחלה ארוך מדי

### ISSUE THREAD

**Issue by erelsgl** [Computer-game-development-course/Where_Is_Sky#3]
אפשר לקצר בכמה דרכים:

א. לקצר משפטים, למשל במקום "You can click the ..." - לכתוב פשוט "Click...".

ב. חלק מההסברים צריכים להיות בגוף המשחק עצמו. למשל:

* ההסבר על החצים צריך להופיע בשלב 1 כשרואים את החיצים.
* ההסבר על המפה צריך להופיע רק אחרי שנפתח עוד חדר, עם חץ לכיוון המפה והסבר "לחץ כאן כדי לעבור לחדר אחר. אולי החתול בחדר אחר...".

**Comment by AlinaZahozi** [comment]
Tutorial was fixed
