### ISSUE TITLE
לסמן חדר חדש כשהוא נפתח

### ISSUE THREAD

**Issue by erelsgl** [Computer-game-development-course/Where_Is_Sky#5]
כשנפתח חדר חדש, במקום רק להגיד "A new room opened", עדיף להציג את המפה ולסמן את החדר החדש שנפתח.

או לפחות לכתוב את שם החדר החדש שנפתח, למשל "Bathroom has opened".

**Comment by AlinaZahozi** [comment]
Tutorial was fixed
