### ISSUE TITLE
גירעון בזמן/ניקוד בכל לחיצה

### ISSUE THREAD

**Issue by Dorshir** [Computer-game-development-course/Where_Is_Sky#7]
לא ברור אם יורד ניקוד לכל לחיצה מיותרת. אין גירעון בזמן. לכן השחקן יכול לעבור על המסך ולהספים בלחיצות עד שהוא אף בטעות לוחץ על החתול ומנצח. אולי להוסיף גירעון בזמן או בנקודות אם לא קיים(בנקודות). ואם אכן הניקוד יורד, כדאי לתת אינדקציה לשחקן על הנקודות היורדות כדי למנוע ממנו לעשות זאת.

**Comment by Dorshir** [comment]
Click spam

**Comment by AlinaZahozi** [comment]
fixed
